### ISSUE TITLE
SQLite Error 14: 'unable to open database file'.

### ISSUE THREAD

**Issue by typetrade** [BruceQiu1996/Socks5Proxy4Net#2]
PS C:\Users\steve\Downloads\Socks5Server\Socks5Server\Server\Socket5_Server> dotnet ef database update
Build started...
Build succeeded.
[16:11:04 ERR] An error occurred using the connection to database 'main' on server 'C:\Users\steve\Downloads\Socks5Server\Socks5Server\Server\Socket5_Server\bin\Debug\net8.0\Data/data.db'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
SQLite Error 14: 'unable to open database file'.
PS C:\Users\steve\Downloads\Socks5Server\Socks5Server\Server\Socket5_Server>

**Comment by typetrade** [comment]
![image](https://github.com/user-attachments/assets/e746c5e0-0371-446c-b242-1f9f17d48c47)

**Comment by typetrade** [comment]
C:\Users\steve\Downloads\Socks5Server\Socks5Server\Server\Socket5_Server\Data\data.db
![image](https://github.com/user-attachments/assets/4e9f139f-a554-402a-b1c2-0cfd3235456c)

PS C:\Users\steve\Downloads\Socks5Server\Socks5Server\Server\Socket5_Server> dotnet ef database update
Build started...
Build succeeded.
[16:17:03 INF] Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
[16:17:03 INF] Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);
[16:17:03 INF] Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
[16:17:03 INF] Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "MigrationId", "ProductVersion"
FROM "__EFMigrationsHistory"
ORDER BY "MigrationId";
[16:17:03 INF] Applying migration '20230514084552_InitDatabase'.
[16:17:03 INF] Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "Users" (
    "Id" TEXT NOT NULL CONSTRAINT "PK_Users" PRIMARY KEY,
    "UserName" TEXT NULL,
    "Password" TEXT NULL,
    "ExpireTime" TEXT NOT NULL,
    "UploadBytes" INTEGER NOT NULL,
    "DownloadBytes" INTEGER NOT NULL,
    "Role" INTEGER NOT NULL
);
[16:17:03 INF] Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230514084552_InitDatabase', '7.0.5');
[16:17:03 INF] Applying migration '20230514085303_AddAdminAccount'.
[16:17:03 INF] Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO "Users" ("Id", "DownloadBytes", "ExpireTime", "Password", "Role", "UploadBytes", "UserName")
VALUES ('1ce5a888-d236-4e0b-9a65-5adbcfd2baf8', 0, '9999-12-31 23:59:59.9999999', '123456', 99, 0, 'Admin');
[16:17:03 INF] Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230514085303_AddAdminAccount', '7.0.5');
Done.
