### ISSUE TITLE
System.Net.Sockets.SocketException (10014): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

### ISSUE THREAD

**Issue by typetrade** [BruceQiu1996/Socks5Proxy4Net#3]
[16:29:51 ERR] System.Net.Sockets.SocketException (10014): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Socks5_Server.ClientStateChangeHandler.HandleRequestProxyAsync(UserToken token) in C:\Users\steve\Downloads\Socks5Server\Socks5Server\Server\Socket5_Server\ClientStateChangeHandler.cs:line 132
   at Appccelerate.StateMachine.AsyncMachine.ActionHolders.ArgumentActionHolder`1.Execute(Object argument)
   at Appccelerate.StateMachine.AsyncMachine.Transitions.TransitionLogic`2.PerformActions(ITransitionDefinition`2 transitionDefinition, ITransitionContext`2 context)

**Comment by BruceQiu1996** [comment]
用管理身份运行cmd，执行netsh winsock reset 重启程序/电脑
